name: Build and Push Docker Image

on:
  release:
    types: [published]
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ vars.PLATFORM_LIST || 'linux/amd64' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: zargarzadehm
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/zargarzadehm/auto-relay

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ vars.PLATFORM_LIST || 'linux/amd64' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
